logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  port: 8081
  servlet:
    context-path: /auth
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/test
    username: root
  h2:
    console:
      enabled: true
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  security:
    user:
      name: user
      password: pass123
user:
  oauth:
    clientId: sanu-admin
    clientSecret: pass
    redirectUris: http://localhost:8082/login/oauth2/code/
    user:
      password: pass123
      username: sanu
