package com.consumer.enums;

public enum Service {

	ELECTRICITY_REPAIRS_AND_FIXES,
	ELECTRICITY_INSTALLATION_SERVICES,
	
	SALON_FOR_MEN_HAIR_CUT,
	SALON_FOR_MEN_CLEAN_SHAVE,
	
	SALON_FOR_WOMEN_HAIR_CUT,
	SALON_FOR_WOMEN_TAN_REMOVAL,
	
	YOGA_AMATEUR,
	YOGA_PROFESSIONAL

}
